### ISSUE TITLE
Upgrade to segment analytics required

### ISSUE THREAD

**Issue by michaelcosta** [segment-integrations/analytics-android-integration-adjust#20]
Based on the thread here https://github.com/segmentio/analytics-android/issues/809 and the issues referenced from within that, the segment anlytics dependency needs to be upgraded to > 4.10.1 https://github.com/segment-integrations/analytics-android-integration-adjust/blob/master/build.gradle#L50

I can quickly toss up a PR for this, but wanted to check first how long a release process might take otherwise I will just fork this for our release if it will be a while.

**Comment by didiergarcia** [comment]
Updated to 4.11.0
