### ISSUE TITLE
Update adjust dependency to latest version

### ISSUE THREAD

**Issue by NickEcho** [segment-integrations/analytics-android-integration-adjust#5]
Adjust has some new functionality to track uninstalls and reinstalls but it requires the sdk version 4.12 or above and this integration depends on 4.11.4: https://github.com/segment-integrations/analytics-android-integration-adjust/blob/master/build.gradle#L43

see: https://docs.adjust.com/en/tracking-app-uninstalls/

**Comment by f2prateek** [comment]
Sorry about not replying here, closed by https://github.com/segment-integrations/analytics-android-integration-adjust/pull/6
