### ISSUE TITLE
Update Adjust SDK to 4.20 since Google is deprecating InstallBroadcast

### ISSUE THREAD

**Issue by emadgit** [segment-integrations/analytics-android-integration-adjust#9]
This is an important breaking change and I hope Segment update Adjust SDK in this library. More information : 

On March 1st, 2020, Google is deprecating InstallBroadcast (also known as the Google Play Store Intent). You can read their official announcement here.

Why is this important?

Adjust attributes Android users using the Google Play Store referrer. This is captured via the Play Referrer API or install_referrer intent broadcast (no longer recommended). After March 1st, the latest Google Play Store app will not broadcast the referrer when a new app is installed. This means the install_referrer will not be able to capture it. In this scenario, Adjust must rely on the device's advertising ID (which is accurate but only available on selected inventories) or on device fingerprinting. Consequently, it is crucial that all apps published on the Google Play Store support the Play Referrer API.

What do you need to do next?

In preparation for this change, make sure you have updated your Adjust SDK to version 4.20 AND updated to Google Play Install Referrer API v1.0 or higher.

SDK 4.12 is the lowest version that supports the Install Play Referrer API.

**Comment by ilansas** [comment]
I agree, we need this !

**Comment by didiergarcia** [comment]
Updated to Adjust SDK 4.33.3.
